---
name: barcode
version: '1.0'
vendor: rhomobile
build: debug
bbver: '4.6'
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.1
  provisionprofile: ''
  codesignidentity: ''
  entitlements: ''
  BundleIdentifier: com.rhomobile.barcode
  BundleURLScheme: barcode
wp:
  productid: 8aea31a0-bc4a-012f-250a-3c07542aa8a3
symbian:
  uid: '0xeb9a0e81'
android:
  version: 2.3.3
  extensions:
  - barcode
extensions:
- barcode
- json
- another-extension
capabilities:
- non_motorola_device
- camera
app_type: rhoelements
sdk: /Users/nishima/.rvm/gems/ruby-1.9.2-p320@rosp/gems/rhodes-3.4.2
